# Generated by Django 2.0.4 on 2018-05-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userController', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WB',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('time', models.DateField(auto_now_add=True)),
                ('plnum', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='WBnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='fansnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='follownum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
