# Generated by Django 2.0.4 on 2018-05-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userController', '0002_auto_20180506_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='WBid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='follow',
            name='followId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='follow',
            name='userId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wb',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
